apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "competences-chart.fullname" . }}
  labels:
{{ include "competences-chart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "competences-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "competences-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "competences-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: POSTGRES__HOST
              value: "postgres-postgresql"
            - name: POSTGRES__PORT
              value: "5432"
            - name: POSTGRES__DATABASE
              value: "competences"
            - name: POSTGRES__USERNAME
              value: "app"
            - name: POSTGRES__PASSWORD
              value: "app13"             
          #livenessProbe:
           # exec:
           #   command: ["/bin/grpc_health_probe", "-addr=:80"]
            #  initialDelaySeconds: 15            
          #readinessProbe:
          #  exec:
          #    command: ["/bin/grpc_health_probe", "-addr=:80"]
           #   initialDelaySeconds: 15 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
